#!/bin/bash

SCALA_VERSION=2.13.10 ALMOND_VERSION=0.13.14

# Install coursier
curl -Lo coursier https://git.io/coursier-cli
chmod +x coursier

# Install almond
./coursier bootstrap \
    -r jitpack \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    --sources --default=true \
    -o almond
./almond --install

rm almond
rm coursier
